[package]
name = "rust-cryptography"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
elliptic-curve = "0.13.8"
hex-literal = "1.0.0"
rand = "0.8"
rsa = "0.9.8"
sha2 = "0.10.9"
sha256 = "1.6.0"

ed25519-dalek = "2.1.1"
# rand = "0.8"
rand_core = "0.6"
base64 = "0.22.1"
